kosi-libs/Kodein

- README.md
Since Kotlin now has public as the default scope I removed cases of public. I also fixed a small typo.
> Removed unnecessary public and small typo fix

- README.md
Unless I'm misunderstanding something, it appears that `singleton` was missing from the example, since it seems that `bind... with` cannot directly be given a lambda, but needs to be given a factory like `singleton`
> Fix typo in transitive dependency example

- README.md
The specified Maven artifact version was missing the patch version number which lead to an error while trying to resolve the Maven artifact (at least in Android Studio / Gradle).
> Fix incomplete library Maven version

- README2.md
- README3.adoc
"contants" -> "constants"
"it's" (with apostrophe) means "it is".  "its" (no apostrophe) is the possessive form of "it". http://its-not-its.info/
Trivial, of course, but distracting.
> Fixed some doc typos

- README3.adoc
The docs say to use `Application` but the example uses `Activity`
> AutoActivityScope Example Fix

- README2.md
- kodein/src/main/kotlin/com/github/salomonbrys/kodein/typeDisp.kt
- kodein/src/test/kotlin/com/github/salomonbrys/kodein/test/test.kt
There are two functions in stdlib specifically introduced to be able to get corresponding Class objects for primitives: [javaObjectType](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.jvm/java-object-type.html) and [javaPrimitiveType](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.jvm/java-primitive-type.html). I've changed some code to use them instead of the old `java.lang.X::class.java` which requires a warning suppressed. I've noticed that the changed code is used only for debug, so no new tests were added.
> Fix typos and use nicer Kotlin API instead of java.lang + warning suppression

- kodein-conf/src/main/kotlin/com/github/salomonbrys/kodein/conf/ConfigurableKodein.kt
Detect StackOverflowError in the following case:
(Note `Kodein.global` reference in constructor and `eagerSingleton`)
class Loop(text: String = Kodein.global.instance())
val module = Kodein.Module {
bind<String>() with singleton { "test" }
bind<Loop>() with eagerSingleton { Loop() }
}
fun main(vararg args: String) {
Kodein.global.addImport(module)
Kodein.global.instance<Loop>()
}
Exception in thread "main" java.lang.StackOverflowError
at TestKt$module$1.invoke(Test.kt)
at TestKt$module$1.invoke(Test.kt)
at com.github.salomonbrys.kodein.Kodein$Builder.<init>(Kodein.kt:303)
at com.github.salomonbrys.kodein.Kodein$Builder.import(Kodein.kt:387)
at com.github.salomonbrys.kodein.conf.ConfigurableKodein$addImport$1.invoke(ConfigurableKodein.kt:144)
at …
> Detect recursive initialization in configurable module

- README3.adoc
- kodein-android/src/main/java/com/github/salomonbrys/kodein/android/KodeinAndroidComponents.kt
Since there's no way the components can know if a binding to `LayoutInflater` has been bound from the android module or not, they add a tag `ACTIVITY_LAYOUT_INFLATER` so they don't run into override errors.
Also, requires that fragment kodein component's activities are also kodein components.
> Fix layout inflater override and require Kodein Activity components

- README3.adoc
- kodein-android/src/main/java/com/github/salomonbrys/kodein/android/KodeinAndroidComponents.kt
Fixes #53. Resolved an issue from original PR with overriding the `Fragment` binding.
> FragmentInjector now injects from parent fragment when present

- DOCUMENTATION.adoc
Fix typo to have consistency in the example
> Fix typo in documentation

- doc/getting-started.adoc
There is no https at github for custom domains :(
Leads to a error if we click on a lick with an unstrusted/not available https certifiaction.
I think it is better to don't show/see that error :)
> Remove https

- doc/core.adoc
There was a mistake in the Kodein 5.0 documentation, with code snippet from Kodein 4.
`refSingleton` was replaced by just `singleton(ref = ...)`
> Fix documentation of referenced singleton

- framework/android/kodein-di-framework-android-support/src/main/java/org/kodein/di/android/support/scopes.kt
- framework/android/kodein-di-framework-android-x/src/main/java/org/kodein/di/android/x/scopes.kt
> Remove the LifecycleOwner from the map of registries after it is destroyed

- doc/getting-started.adoc
There is mistake in example in getting started document
> fix typo on document example

- demo/demo-android/src/main/java/kodein/di/demo/MainFragment.kt
- framework/android/kodein-di-framework-android-core/src/main/java/org/kodein/di/android/scopes.kt
- kodein-di-core/src/commonMain/kotlin/org/kodein/di/internal/KodeinTreeImpl.kt
I found a bug in the Android demo project, where on first load, MainFragment's coffeeMaker was the same instance as MainActivity's, but on Activity restarts the MainFragment would end up creating a new CoffeeMaker instance instead of using the Activity's version.
See dcdbe9f for a demonstration of this effect.
The underlying problem was that the translator wasn't being cached when the Fragment finds the CoffeeMaker the first time. Fix in ad14180.
There was also a minor issue in the Android demo where the app would crash on rotate due to a view memory leak, which I fixed in 1a2530b.
> Fix for bug getting cached instances with translated contexts

- demo/demo-ktor/src/main/kotlin/KodeinApplication.kt
- framework/ktor/kodein-di-framework-ktor-server-jvm/src/test/kotlin/org/kodein/di/ktor/KtorApplication.kt
- framework/ktor/kodein-di-framework-ktor-server-jvm/src/test/kotlin/org/kodein/di/ktor/KtorTests.kt
Binding a `java.security.SecureRandom` give a `NonBlocking` at retrieval in Ktor pipeline (=coroutine).
Moving to `java.util.Random` fix the issue.
Maybe an other inspiration to go for Kodein-DI coroutine compatibility ?
> fix ktor test failure

- framework/ktor/kodein-di-framework-ktor-server-jvm/src/test/kotlin/org/kodein/di/ktor/KtorTests.kt
avoid time lag between to API calls as we were comparing session, expiration timestamps can have interval.
> ktor fix failing test_03_session_scoped

- doc/ktor.adoc
- framework/ktor/kodein-di-framework-ktor-server-controller-jvm/src/main/kotlin/org/kodein/di/ktor/controller/controller.kt
- framework/ktor/kodein-di-framework-ktor-server-controller-jvm/src/main/kotlin/org/kodein/di/ktor/controller/exentsions.kt
- framework/ktor/kodein-di-framework-ktor-server-controller-jvm/src/main/kotlin/org/kodein/di/ktor/controller/feature.kt
- framework/ktor/kodein-di-framework-ktor-server-controller-jvm/src/test/kotlin/org/kodein/di/ktor/controller/KtorApplication.kt
- framework/ktor/kodein-di-framework-ktor-server-controller-jvm/src/test/kotlin/org/kodein/di/ktor/controller/KtorControllerTests.kt
- framework/ktor/kodein-di-framework-ktor-server-controller-jvm/src/test/kotlin/org/kodein/di/ktor/controller/controller.kt
> Following the issue #206 
Adding two extension functions to be able to install `KodeinController` routes inside the Ktor routing system.
> Allowing us to write
```kotlin
routing {
controller { FirstController(instance()) }
route {
controller { SecondController(instance()) }
}
authenticate("name") {
controller("/protected") { KodeinControllerImpl(instance()) }
}
}
```
As the `KodeinController` might always be singletons, the new extension functions cover all we need, without extra work.
So, I suggest to deprecate `KodeinControllerFeature` as we don't need to bind `KodeinController` inside Kodein.
> Modifying Ktor routing with KodeinController

- kodein-di-core/src/commonMain/kotlin/org/kodein/di/internal/KodeinBuilderImpl.kt
- kodein-di-erased/src/commonTest/kotlin/org/kodein/di/erased/ErasedTests_10_Module.kt
- kodein-di-generic-jvm/src/test/kotlin/org/kodein/di/generic/GenericJvmTests_10_Module.kt
When extending a container, we add to the `importedModules` of the current `MainBuilder` the modules of the copied bindings.
This is the more straightforward solution as we don't have the modules anynore, as long as the container as been built. We only have the reference name of the modules, in the bindings themself, through the var `KodeinDefining#fromModule`.
> Allow extended container to use imported modules

- doc/core.adoc
- doc/getting-started.adoc
Just a few typos and one adoc error I found when reading the documentation.
> [DOC] Fix typos

- doc/core.adoc
- kodein-di-core/src/commonMain/kotlin/org/kodein/di/tuples.kt
- kodein-di-erased/src/commonMain/kotlin/org/kodein/di/erased/EMulti.kt
- kodein-di-erased/src/commonTest/kotlin/org/kodein/di/erased/ErasedTests_20_1_MultiArguments_deprecated.kt
- kodein-di-erased/src/commonTest/kotlin/org/kodein/di/erased/ErasedTests_20_2_MultiArguments.kt
- kodein-di-erased/src/commonTest/kotlin/org/kodein/di/erased/ErasedTests_20_MultiArguments.kt
- kodein-di-generic-jvm/src/main/kotlin/org/kodein/di/generic/GMulti.kt
What have been done:
- Depreciate factories retrieval functions
- `factory2()` / `factory3()` / `factory4()` / `factory5()`
- Depreciate factories and multiton functions with multi-arg only
- `factory(MultiX)` / `multiton(MultiX)`
- Depreciate `MultiX` tuples as they are used only for multi-arg factories
- Depreciate multi-arg tests
- Create new tests with data class usage instead of multi-arg
- Adapt documentation (should be revamped after removal as we reference multi-arg as deprecated)
> Depreciate multi-argument factories

- README.md
The doc link on the README appears to link to a version of the docs that suggests installing an unreleased version of Kodein (7.2.0) which does not appear to be on jcenter. 
```
Could not find org.kodein.di:kodein-di:7.2.0.
Required by:
project :
```
> change doc link from 7.2.0 to 7.1.0 as 7.2.0 appears to be unreleased.

- doc/modules/framework/pages/android.adoc
The documentation itself says:
> For that, View Models need to implement `AndroidViewModel`.
But then in the code example proceeds to implement `ApplicationViewModel`.
`class MyViewModel(app: Application) : ApplicationViewModel(app), DIAware`
As a side note: 
Does the `override val di by di()` inside the viewModel perhaps need to be replaced with  `override val di by di(app)`?
Or am I just missing something?
> Small error in Android documentation

- doc/modules/framework/pages/tornadofx.adoc
Added missing group ID for the kodein-di-framework-tornadofx-jvm artifact.
> Corrected artifact coordinates.

- framework/android/kodein-di-framework-android-core/src/main/java/org/kodein/di/android/closest.kt
- framework/compose/kodein-di-framework-compose/build.gradle.kts
- framework/compose/kodein-di-framework-compose/src/androidMain/kotlin/org/kodein/di/compose/androidContext.kt
- framework/compose/kodein-di-framework-compose/src/commonMain/kotlin/org.kodein.di.compose/CompositionLocal.kt
- framework/compose/kodein-di-framework-compose/src/commonMain/kotlin/org.kodein.di.compose/retrieving.kt
- framework/compose/kodein-di-framework-compose/src/commonMain/kotlin/org.kodein.di.compose/subDI.kt
- framework/compose/kodein-di-framework-compose/src/commonMain/kotlin/org.kodein.di.compose/withDI.kt
- framework/compose/kodein-di-framework-compose/src/jvmMain/kotlin/org/kodein/di/compose/jvmContext.kt
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle.kts
- DI from Android context is now automatic
- `contextDI` is now renamed `androidContextDI` (to differentiate between DI context & Android context)
- Updated Android `closestDI` to throw a meaningful exception when failing (rather than a non-semantic ClassCastException)
- `LocalDI` is now internal, `localDI` (which defers to android context DI when there is no DI in the compose tree) must be used instead.
- Compose `instance`, `provider` & `factory` retrieval functions are renamed `rememberInstance()`, `rememberProvider()` & `rememberFactory()` (to align with every other compose function that uses `remember`).
- Added `onDIContext` to attach a DI context to a compose tree.
> Multiple enhancements for Compose.

- doc/modules/framework/pages/android.adoc
Fixed a typo in the code block of the Android framework documentation. This is impacting version 7.8.0 and 7.7.0 of the documentation. 
You can find the typo here: https://docs.kodein.org/kodein-di/7.8/framework/android.html#_view_models
> Fixed typo in the Android framework docs

- doc/modules/extension/pages/configurable.adoc
While using the instructions, I noticed that the package name was wrong. Here is the corrected information for JVM projects.
> Fixing packages names for kodein-di-conf
